export const typingPrompts = [
    "The quick brown fox jumps over the lazy dog with a graceful leap, showcasing its agility and speed.",
    "Pack my box with five dozen liquor jugs and ensure they are all properly secured before shipment.",
    "Sphinx of black quartz, judge my vow to always strive for excellence in all my endeavors, no matter how difficult.",
    "How quickly daft jumping zebras vex the peaceful meadow, disrupting the serenity with their erratic movements.",
    "Jived fox nymph grabs quick waltz, displaying an unexpected talent for dance with elegant and lively steps.",
    "Crazy Fredrick bought many very exquisite opal jewels at the auction, hoping to impress his very wealthy friends with his purchase.",
    "The five boxing wizards jump quickly over the low hurdles, preparing for the grand championship with fierce determination and focus.",
    "My girl wove six dozen plaid jackets before she quit her job at the textile factory, showcasing her incredible speed and skill.",
    "A wizard’s job is to vex chumps quickly in fog, using mysterious spells and incantations to confuse and disorient their targets.",
    "We promptly judged antique ivory buckles for the next prize, carefully examining every detail of the craftsmanship and condition of the artifacts.",
    "Lazy movers jacked up the quaint big zebra box, struggling to lift the heavy package due to their lack of physical strength and stamina.",
    "Few black taxis drive up major quartz highways during the rush hour, avoiding the congested roads and preferring the less traveled paths.",
    "Jack quietly moved the box of woven quilts into the attic, ensuring that he did not disturb anyone who might be sleeping within the house.",
    "The vixen jumped quickly over the lazy brown fox, displaying a rare show of boldness and confidence in her natural habitat.",
    "Six big devils from Japan quickly forgot how to waltz, causing them to stumble and trip as they attempted the complicated dance moves.",
    "Five quacking zephyrs jolt my wax bed, creating an unsettling experience as the gentle breezes cause the bed to shake and vibrate.",
    "The sky above the port was the color of television, tuned to a dead channel, a bizarre and unsettling view that defied logic and expectation.",
    "She sells seashells by the seashore, repeating the tongue twister as a fun activity during her leisurely walk on the sandy beach.",
    "Peter Piper picked a peck of pickled peppers, a classic tongue twister that challenges the speed and precision of the speaker's articulation.",
    "The big dog barked loudly at the mailman, a common occurrence that did not faze the delivery person as they continued their daily route.",
];
